var labobs robs pinfobs dy dc dinve dw eta_w_ma eta_p_ma zcapf rkf kf pkf cf invef yf labf wf rrf mc zcap rk k_s q c i y l pinf w r eps_a eps_b eps_g eps_i eps_r eps_p eps_w kpf k;

varexo eta_a eta_b eta_g  eta_i eta_r eta_p eta_w;

parameters curv_w rho_ga curv_p l_bar pi_bar beta_const Mu_w Mu_p alpha psi phi delta sigma_c lambda phi_p iota_w xi_w iota_p xi_p sigma_l phi_w r_pi r_dy r_y rho
	rho_a rho_b rho_g rho_i rho_r rho_p rho_w gamma_bar G;

delta = 0.025;
phi_w = 1.5;
G = 0.18;
curv_p = 10;
curv_w = 10;
phi = 6.3325;
sigma_c = 1.2312;
lambda = 0.7205;
xi_w = 0.7937;
sigma_l = 2.8401;
xi_p = 0.7813;
iota_w = 0.4425;
iota_p = 0.3291;
psi = 0.2648;
phi_p = 1.4672;
r_pi = 1.7985;
rho = 0.8258;
r_y = 0.0893;
r_dy = 0.2239;
pi_bar = 0.7;
beta_const = 0.7420;
l_bar = 1.2918;
gamma_bar = 0.3982;
alpha = 0.24;
rho_a = .9676;
rho_b = .2703;
rho_g = .9930;
rho_i = .5724;
rho_r = .3;
rho_p = .8692;
rho_w = .9546;
Mu_p = .7652;
Mu_w = .8936;
rho_ga = 0.05;
